### ISSUE TITLE
CleanWebpackPlugin is not a function

### ISSUE THREAD

**Issue by diegodesouza** [HashemKhalifa/webpack-react-boilerplate#128]
Hello, I just cloned the project, ran `npm install` and `npm run build` and am getting the current error. 

`TypeError: CleanWebpackPlugin is not a constructor`

is this is a know issue?

**Comment by HashemKhalifa** [comment]
@diegodesouza Kindly pull the latest changes, already fixed.

Thanks for reporting it!
