### ISSUE TITLE
Remove "@babel/plugin-transform-react-inline-elements" plugin in the development environment

### ISSUE THREAD

**Issue by cj0x39e** [HashemKhalifa/webpack-react-boilerplate#180]
Because:
> This transform should be enabled only in production (e.g., just before minifying your code) because, although it improves runtime performance, **it makes warning messages more cryptic and skips important checks that happen in development mode, including propTypes.**

[babel-plugin-transform-react-inline-elements](https://babeljs.io/docs/en/babel-plugin-transform-react-inline-elements)

**Comment by HashemKhalifa** [comment]
@cj0x39e fixed thanks :)
