### ISSUE TITLE
Commit failed with error

### ISSUE THREAD

**Issue by joshuarobs** [HashemKhalifa/webpack-react-boilerplate#194]
When I try to commit all of the files, I get an error:

Warning: Setting pre-commit script in package.json > scripts will be deprecated Please move it to husky.hooks in package.json, a .huskyrc file, or a husky.config.js file Or run ./node_modules/.bin/husky-upgrade for automatic update See https://github.com/typicode/husky for usage husky > pre-commit (node v10.16.0) Stashing changes... [started] Stashing changes... [skipped] → No partially staged files found... Running linters... [started] Running tasks for *.{js,jsx,css,md} [started] prettier --write --single-quote [started] prettier --write --single-quote [completed] eslint --fix [started] eslint --fix [failed] → Running tasks for *.{js,jsx,css,md} [failed] → Running linters... [failed] ✖ eslint --fix found some errors. Please fix them and try committing again. /Users/joshua/WebstormProjects/it-app/client/babel.config.js 1:18 warning Unexpected unnamed function func-names /Users/joshua/WebstormProjects/it-app/client/src/components/hello-world/hello-world.css 1:1 error Parsing error: Unexpected token > 1 | .hello-world { | ^ 2 | margin-top: 10rem; 3 | font-size: 2rem; 4 | text-align: center; ✖ 2 problems (1 error, 1 warning) husky > pre-commit hook failed (add --no-verify to bypass)

I get the same error attempting to commit in VSCode.

This is the cause I think:

✖ eslint --fix found some errors. Please fix them and try committing again.

/Users/joshua/WebstormProjects/it-app/client/babel.config.js
1:18  warning  Unexpected unnamed function  func-names

/Users/joshua/WebstormProjects/it-app/client/src/components/hello-world/hello-world.css
1:1  error  Parsing error: Unexpected token

> 1 | .hello-world {
  | ^
2 |   margin-top: 10rem;
3 |   font-size: 2rem;
4 |   text-align: center;

✖ 2 problems (1 error, 1 warning)

**Comment by HashemKhalifa** [comment]
@joshuarobs can you give me a `codesandbox`

**Comment by HashemKhalifa** [comment]
also please pull the latest update from master!

**Comment by joshuarobs** [comment]
I pulled the latest changes as you suggested, and committing and pushing the boilerplate code into an empty repo (with only a readme file) works fine, thank you for the quick fix Hashem! I'll try and see if I can do the same and put the client side code into its own folder in my server repo, hopefully it works

**Comment by joshuarobs** [comment]
@HashemKhalifa Unfortunately, when I try to run `npm start` on the boilerplate code (on its own), I get a blank screen on the web browser with no hello world text.

I got this error too:

Joshuas-MBP:test joshua$ npm start

> minimal-webpack-react@2.0.0 start /Users/joshua/WebstormProjects/test
> cross-env NODE_ENV=development webpack-dev-server --open

 10% building 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:8081/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/joshua/WebstormProjects/test/build                                   10% building 6/14 modules 8 active ...test/src/index.js✖ ｢wdm｣: Hash: f06656979d8cba7d0d0d                      Version: webpack 4.35.3
Time: 697ms
Built at: 07/17/2019 11:36:06 PM
     Asset       Size  Chunks             Chunk Names
index.html  391 bytes          [emitted]  
   main.js    390 KiB    main  [emitted]  main
Entrypoint main = main.js
[0] multi (webpack)-dev-server/client?http://localhost (webpack)/hot/dev-server.js ./src/index.jsx 52 bytes {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost] (webpack)-dev-server/client?http://localhost 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.77 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.63 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {main} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.34 KiB {main} [built]
[./src/index.jsx] 841 bytes {main} [built] [failed] [1 error]
    + 20 hidden modules

ERROR in ./src/index.jsx
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: No ESLint configuration found in /Users/joshua/WebstormProjects/test/src.
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/joshua/WebstormProjects/test/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:406:19)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/joshua/WebstormProjects/test/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:248:21)
    at CLIEngine.executeOnText (/Users/joshua/WebstormProjects/test/node_modules/eslint/lib/cli-engine/cli-engine.js:857:47)
    at lint (/Users/joshua/WebstormProjects/test/node_modules/eslint-loader/index.js:278:17)
    at Object.module.exports (/Users/joshua/WebstormProjects/test/node_modules/eslint-loader/index.js:273:21)
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/template.html] 541 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.

I'm not sure, but maybe it's a missing eslint file in src folder?

**Comment by joshuarobs** [comment]
I re cloned the repo and ran npm start and everything is working again. I'll do one final check committing and pushing the files to git, before I'll close this issue as I think its been fixed

**Comment by joshuarobs** [comment]
I did quiet a few tests, copying the repo, npm install and npm run. Earlier in some of my cases sometimes the build would fail for some reason. Now recently, the build works fine. This was running npm start in the folder I downloaded, in a new folder (+ copy and paste from the downloaded one) and an empty repo folder (+ copy and paste from the downloaded one).

Right now if I try to create a blank repo on Github, clone it, copy the files over, the build works fine, however, if I try to commit the files, I get the following error below:

Looking for git in: /usr/local/bin/git
Using git 2.22.0 from /usr/local/bin/git
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: /Users/joshua/WebstormProjects/it-app-client
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git commit --quiet --allow-empty-message --file -
husky > pre-commit (node v10.16.0)
Stashing changes... [started]
Stashing changes... [skipped]
→ No partially staged files found...
Running linters... [started]
Running tasks for *.{js,jsx,css,md} [started]
prettier --write --single-quote [started]
prettier --write --single-quote [completed]
eslint --fix [started]
eslint --fix [failed]
→ 
Running tasks for *.{js,jsx,css,md} [failed]
→ 
Running linters... [failed]



✖ eslint --fix found some errors. Please fix them and try committing again.

/Users/joshua/WebstormProjects/it-app-client/CODE_OF_CONDUCT.md
1:2  error  Parsing error: Unexpected character '#'

> 1 | # Contributor Covenant Code of Conduct
  |  ^
2 | 
3 | ## Our Pledge
4 |

/Users/joshua/WebstormProjects/it-app-client/babel.config.js
1:18  warning  Unexpected unnamed function  func-names

/Users/joshua/WebstormProjects/it-app-client/readme.md
1:2  error  Parsing error: Unexpected character '#'

> 1 | ## Webpack react minimal boilerplate
  |  ^
2 | 
3 | <p align="center">
4 |     <img alt="dependencies" title="dependencies" src="https://img.shields.io/david/hashemkhalifa/webpack-react-boilerplate.svg" >

/Users/joshua/WebstormProjects/it-app-client/src/components/hello-world/hello-world.css
1:1  error  Parsing error: Unexpected token

> 1 | .hello-world {
  | ^
2 |   margin-top: 10rem;
3 |   font-size: 2rem;
4 |   text-align: center;

✖ 4 problems (3 errors, 1 warning)

{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
husky > pre-commit hook failed (add --no-verify to bypass)
> git config --get-all user.name
> git config --get-all user.email


Could you try to create a new empty repo, copy the files over, npm install, npm start and commit the files? I always get this error when I try to do the commit part. Also I tried to load your repo in `codesandbox` but it wouldn't let me run commands on the terminal

**Comment by HashemKhalifa** [comment]
Do you have `git` and `npm `installed? 
you can fork the repo and do your changes and send me the link

**Comment by joshuarobs** [comment]
I think I have fixed the issue on my end. I don't know if other people may still run into the same problem.

I updated the package.json lint-staged part so that eslint wouldn't run on the files that it doesn't need to run on:

`
"lint-staged": {
    "*.{js,jsx}": [
      "prettier --write --single-quote",
      "eslint --fix",
      "git add"
    ],
    "*.{css,scss}": [
      "prettier --write --single-quote",
      "git add"
    ],
    "*.{md}": [
      "prettier --write --single-quote",
      "git add"
    ]
  },
`

style lint may be added to the css,scss part.

**Comment by HashemKhalifa** [comment]
@joshuarobs thanks, I added `scss` to the lint-staged
