### ISSUE TITLE
Not Working in IE

### ISSUE THREAD

**Issue by jeetu241295** [HashemKhalifa/webpack-react-boilerplate#75]
I have cloned the repository. done yarn start. Opend it IE-11. This is the issue. Even i tested in some other IE versions its showing the same issue.

![image](https://user-images.githubusercontent.com/31988265/56711299-ca8ba880-6747-11e9-8fde-105c009e9d33.png)

**Comment by HashemKhalifa** [comment]
Would you kindly give me more details?
Which IE Version?

**Comment by jeetu241295** [comment]
> Would you kindly give me more details?
> Which IE Version?
 Updated the Issue

**Comment by jeetu241295** [comment]
`
[
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            "ie >= 11",
            "last 2 Chrome versions",
            "last 2 Firefox versions",
            "last 2 Safari versions",
            "last 2 ChromeAndroid versions",
            "last 2 Edge versions",
            "last 2 iOS versions"
          ]
        },
        "useBuiltIns": "entry"
      }
    ],
`
add these in the .babelrc presets. Its working for me now.
